import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Cognición & Ser</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Image
					src="/LOGO-colorsinfondo.png"
					width={200}
					height={200}
					alt="Cognición & Ser Logo"
					className={styles.logo}
				/>
				<p className={styles.description}>
					Servicios de Psicología, Neuropsicología y Psiquiatría
				</p>
				<p className={styles.description}>Atención presencial y virtual</p>

				<div className={styles.grid}>
					<button className={styles.card}>
						<h2>Quiénes somos &rarr;</h2>
						<p>Conozca acerca de nosotros</p>
					</button>

					<button className={styles.card}>
						<h2>Nuestros Servicios &rarr;</h2>
						<p>Conozca nuestro portafolio de servicios</p>
					</button>

					<button className={styles.card}>
						<h2>Separe una cita &rarr;</h2>
						<p>Contrate nuestros servicios</p>
					</button>

					<button
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Contáctenos &rarr;</h2>
						<p>Conozca nuestros canales de atención</p>
					</button>
				</div>
			</main>

			<footer className={styles.footer}>
				Cognición & Ser{" "}
				<span className={styles.logo}>
					<Image
						src="/LOGOblanco-sinfondp.png"
						alt="Cognición y Ser Logo"
						width={72}
						height={72}
					/>
				</span>
			</footer>
		</div>
	);
}
